---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
# TODO: seprate UT with integration test
- name: test
  image: java:openjdk-8
  environment:
    GRADLE_USER_HOME: ~/.gradle
  commands:
    # wait for db up
    - sleep 5
    - dbHost=database ./gradlew test --info

- name: sonar-analysis
  image: gradle:jdk8
  commands:
    - ./gradlew sonarqube \
        -Dsonar.projectKey=artificerpi_spring-petclinic-mybatis \
        -Dsonar.organization=artificerpi-github \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${SONARCLOUD_TOKEN}

services:
- name: database
  image: mysql:5.7
  environment:
    # TODO: need to use other user
    MYSQL_ROOT_PASSWORD: petclinic
    MYSQL_DATABASE: petclinic
    MYSQL_USER: tester
    MYSQL_PASSWORD: petclinic
...