mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
    - MYSQL_USER=pc
    - MYSQL_PASSWORD=petclinic
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
