spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  messages:
    basename: messages/messages

server:
  port: 9966
  servlet:
    contextPath: /petclinic

mybatis:
 mapper-locations: classpath*:mapper/*Mapper.xml